export const SET_SIGN_IN_USER = 'SET_SIGN_IN_USER';
export const SHOW_CART_DROPDOWN = "SHOW_CART_DROPDOWN";
export const ADD_TO_CART = "ADD_TO_CART";
export const CLEAR_FROM_CART = "CLEAR_FROM_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
